// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqXPfjgLwWoaPD9SSHanou-SO9u15yfs',
    appId: '1:6472919043:web:515d83a803791db899c636',
    messagingSenderId: '6472919043',
    projectId: 'fintrack-app-9a993',
    authDomain: 'fintrack-app-9a993.firebaseapp.com',
    storageBucket: 'fintrack-app-9a993.firebasestorage.app',
    measurementId: 'G-2B7M8T8X20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WErMcTNSrjlQ4n-Ceht87D0c-d41Iug',
    appId: '1:6472919043:android:c5add8d9bec6f8a699c636',
    messagingSenderId: '6472919043',
    projectId: 'fintrack-app-9a993',
    storageBucket: 'fintrack-app-9a993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkRl2QNHFVkjEWb82kBLBFwcfPWbkzOo',
    appId: '1:6472919043:ios:e0ed4aae5d14fbac99c636',
    messagingSenderId: '6472919043',
    projectId: 'fintrack-app-9a993',
    storageBucket: 'fintrack-app-9a993.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkRl2QNHFVkjEWb82kBLBFwcfPWbkzOo',
    appId: '1:6472919043:ios:e0ed4aae5d14fbac99c636',
    messagingSenderId: '6472919043',
    projectId: 'fintrack-app-9a993',
    storageBucket: 'fintrack-app-9a993.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqXPfjgLwWoaPD9SSHanou-SO9u15yfs',
    appId: '1:6472919043:web:f71822a2f09c50b599c636',
    messagingSenderId: '6472919043',
    projectId: 'fintrack-app-9a993',
    authDomain: 'fintrack-app-9a993.firebaseapp.com',
    storageBucket: 'fintrack-app-9a993.firebasestorage.app',
    measurementId: 'G-N07XH9JFJ7',
  );
}
